services:
  postgresql:
    image: "postgres:17-alpine"
    restart: no
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  mongodb:
    image: "mongo"
    restart: no
    environment:
      - MONGO_INITDB_DATABASE=db_tasks
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
        - "27017:27017"