server:
  port: 8083

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your@gmail.com
    password: password-generated-with-apps-password
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
              enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
    protocol: smtp
  thymeleaf:
    enabled: true

email:
  sender: your@gmail.com
  senderName: "Sender Name Here"